baseurl: "/"
languageCode: "en-us"
title: "wingstone's blog"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Categories
      url: "categories/"
      weight: 2
    - name: Tags
      url: "tags/"
      weight: 3
    - name: Archives
      url: "archives/"
      weight: 4
    - name: About
      url: "about/"
      weight: 5
    - name: Subscribe
      url: "index.xml"

params:
  favicon: "icons/16.png"
  description: "wingtone's blog website."
  footer: "&copy; [wingstone](https://wingstone.github.io) 2020 -- {Year} | [Github](https://github.com/wingstone) | [Zhihu](https://www.zhihu.com/people/wu-zhu-32-40) | [Shadertoy](https://www.shadertoy.com/user/wingstone)"

markup:
  highlight:
    codeFences: true
  goldmark:
    renderer:
      unsafe: true
