baseurl = "/"
languageCode = "en-us"
title = "wingstone's blog"
theme = "hugo-xmin"
paginate = 9
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = [
  "\\.Rmd$",
  "\\.Rmarkdown$",
  "_cache$",
  "\\.knit\\.md$",
  "\\.utf8\\.md$"
]

[permalinks]
note = "/note/:year/:month/:day/:slug/"
post = "/post/:year/:month/:day/:slug/"

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "Categories"
url = "categories/"
weight = 2

[[menu.main]]
name = "Tags"
url = "tags/"
weight = 3

[[menu.main]]
name = "Archives"
url = "archives/"
weight = 4

[[menu.main]]
name = "About"
url = "about/"
weight = 5

[[menu.main]]
name = "Subscribe"
url = "index.xml"

[Params]
favicon = "icons/16.png"
description = "wingtone's blog website."
footer = "&copy; [wingstone](https://wingstone.github.io) 2020 -- {Year} | [Github](https://github.com/wingstone) | [Zhihu](https://www.zhihu.com/people/wu-zhu-32-40) | [Shadertoy](https://www.shadertoy.com/user/wingstone)"
enableGitalk = true

[Params.Gitalk]
clientID = "6ac25831f8084638e036" # Your client ID
clientSecret = "ba798581fc341f62243d29d9be3d56d58cb38b74" # Your client secret
repo = "wingstone.github.io" # The repo to store comments
owner = "wingstone" # Your GitHub ID
admin = "wingstone" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
id = "wingstone.github.io" # The unique id of the page.
labels = "gitalk" # Github issue labels. If you used to use Gitment, you can change it
perPage = 15 # Pagination size, with maximum 100.
pagerDirection = "last" # Comment sorting direction, available values are 'last' and 'first'.
createIssueManually = false # If it is 'false', it is auto to make a Github issue when the administrators login.
distractionFreeMode = false # Enable hot key (cmd|ctrl + enter) submit comment.
proxy = https://gitalkserver.wingstone.workers.dev/?https://github.com/login/oauth/access_token

[markup]
defaultMarkdownHandler = "goldmark"

[markup.highlight]
codeFences = true
guessSyntax = true
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.extensions]
footnote = true